### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [dh4/WeatherRadar#2]
Greetings @dh4 , 

I would like to propose design for a logo/icon for your project. It is my honor to work with you and for your project. Thank you and good luck to your application

-Jibbie Eguna

**Comment by dh4** [comment]
What ideas do you have with the logo? I'm fairly happy with the current one. It's unique from just about every other application of this type (in that it's not a green/yellow/red storm cell in some sort of circle or grid).
