### ISSUE TITLE
RIDGE I is discontinued

### ISSUE THREAD

**Issue by turboencabulator** [dh4/WeatherRadar#7]
https://www.weather.gov/media/notification/pdf2/scn20-85ridge11aab.pdf
https://www.weather.gov/radarfaq

All the old radar image products have been discontinued since December 16th.  Maybe the images at https://mrms.ncep.noaa.gov/data/RIDGEII/ can be used instead?

**Comment by dh4** [comment]
I'm aware of this but using the new images would require re-writing a lot of the application which I don't have time for right now. I'll add a notice to the front page. Thanks for reporting.

**Comment by turboencabulator** [comment]
For the lite images, it might be enough to change the URLs to point to the files here:
https://radar.weather.gov/ridge/lite/
I believe they've been making improvements to those images in the past few days, they now include cities/borders/roads, and I think the mosaics are also new.

**Comment by dh4** [comment]
Thanks for the update! Yes those images look much easier to implement as I wouldn't have to worry about map data.

I'm going to be busy the next couple weeks but will try to work on implementing them when I have a chance.

**Comment by dh4** [comment]
This is working now with the new images and deployed/released. May take a couple days for the new version to show up on F-Droid if you're getting it from there.
